source venv/bin/activate
python IO_performance_testing.py startIOHeavyTestInMain
python IO_performance_testing.py startIOHeavyTestInBackground
python IO_performance_testing.py startIOHeavyTestInGreenlet
python IO_performance_testing.py startIOHeavyTestInParallel
python IO_performance_testing.py startIOHeavyTestInConcurrent
python performance_testing.py startCPUHeavyTestInMain
python performance_testing.py startCPUHeavyTestInBackground
python performance_testing.py startCPUHeavyTestInGreenlet
python performance_testing.py startCPUHeavyTestInParallel
python performance_testing.py startCPUHeavyTestInConcurrent
deactivate
